/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/faq": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Получить все FAQ
     * @description Возвращает список всех вопросов и ответов FAQ, которые использует бот.
     */
    get: operations["get_all_faqs_api_v1_faq_get"]
    put?: never
    /**
     * Создать FAQ
     * @description Создает новый вопрос FAQ и автоматически применяет его для новых запросов к боту.
     */
    post: operations["create_faq_api_v1_faq_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/faq/{index}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Обновить FAQ по индексу
     * @description Обновляет существующий FAQ элемент по его позиции (индексу) в списке.
     */
    put: operations["update_faq_api_v1_faq__index__put"]
    post?: never
    /**
     * Удалить FAQ по индексу
     * @description Удаляет существующий FAQ элемент по его позиции (индексу) в списке.
     */
    delete: operations["delete_faq_api_v1_faq__index__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/users/count-stats": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Users Count Stats */
    get: operations["get_users_count_stats_api_v1_users_count_stats_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/messages": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Messages
     * @description Возвращает список сообщений и ответов бота.
     */
    get: operations["get_messages_api_v1_messages_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * FaqItem
     * @description Схема для отдельного элемента FAQ.
     */
    FaqItem: {
      /**
       * Question
       * @description Основной вопрос
       */
      question: string
      /**
       * Aliases
       * @description Альтернативные формулировки (синонимы) вопроса
       */
      aliases?: string[]
      /**
       * Answer
       * @description Текст ответа
       */
      answer: string
    }
    /**
     * FaqListResponse
     * @description Схема ответа для списка FAQ-вопросов.
     */
    FaqListResponse: {
      /**
       * Items
       * @description Список вопросов-ответов
       */
      items: components["schemas"]["FaqItem"][]
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** MessageResponse */
    MessageResponse: {
      /** Id */
      id: string
      /** User Id */
      user_id: number
      /** Session Id */
      session_id: string
      /** User Text */
      user_text: string
      /** Bot Response */
      bot_response: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** UserCountStatsResponse */
    UserCountStatsResponse: {
      /** Day */
      day: number
      /** Week */
      week: number
      /** Month */
      month: number
      /** Year */
      year: number
      /** All Time */
      all_time: number
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_all_faqs_api_v1_faq_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FaqListResponse"]
        }
      }
    }
  }
  create_faq_api_v1_faq_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["FaqItem"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FaqItem"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_faq_api_v1_faq__index__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        index: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["FaqItem"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FaqItem"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_faq_api_v1_faq__index__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        index: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_users_count_stats_api_v1_users_count_stats_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserCountStatsResponse"]
        }
      }
    }
  }
  get_messages_api_v1_messages_get: {
    parameters: {
      query?: {
        /** @description Фильтр по user_id */
        user_id?: number | null
        /** @description Количество записей */
        limit?: number
        /** @description Смещение */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageResponse"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
}
