/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations["login_api_v1_auth_login_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/register": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Register */
    post: operations["register_api_v1_auth_register_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Me */
    get: operations["get_me_api_v1_auth_me_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/invite": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Invite */
    post: operations["create_invite_api_v1_auth_invite_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/admins": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Admins */
    get: operations["list_admins_api_v1_auth_admins_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/admins/{admin_id}/deactivate": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Deactivate Admin */
    patch: operations["deactivate_admin_api_v1_auth_admins__admin_id__deactivate_patch"]
    trace?: never
  }
  "/api/v1/topics/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Получить все темы
     * @description Получить список всех активных тем.
     */
    get: operations["get_topics_api_v1_topics__get"]
    put?: never
    /**
     * Создать новую тему
     * @description Создает новую тему.
     *
     *     - **label**: уникальное название темы
     *     - **description**: опциональное описание
     *     - **is_active**: активна ли тема при создании (по умолчанию True)
     */
    post: operations["create_topic_api_v1_topics__post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/topics/{topic_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Получить тему по ID
     * @description Получает тему по её ID.
     */
    get: operations["get_topic_api_v1_topics__topic_id__get"]
    /**
     * Обновить тему
     * @description Обновляет тему по ID.
     *
     *     - **label**: новое название (опционально)
     *     - **description**: новое описание (опционально)
     *     - **is_active**: изменить статус активности (опционально)
     */
    put: operations["update_topic_api_v1_topics__topic_id__put"]
    post?: never
    /**
     * Удалить тему
     * @description Удаляет (деактивирует) тему по ID.
     *
     *     Примечание: тема не удаляется из БД, а деактивируется (is_active = False)
     *     для сохранения целостности исторических данных.
     */
    delete: operations["delete_topic_api_v1_topics__topic_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/abbrev": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Получить все аббревиатуры */
    get: operations["get_all_api_v1_abbrev_get"]
    put?: never
    /** Добавить аббревиатуру */
    post: operations["create_api_v1_abbrev_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/abbrev/{item_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Обновить аббревиатуру по ID */
    put: operations["update_api_v1_abbrev__item_id__put"]
    post?: never
    /** Удалить аббревиатуру по ID */
    delete: operations["delete_api_v1_abbrev__item_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/faq": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Получить все FAQ */
    get: operations["get_all_faqs_api_v1_faq_get"]
    put?: never
    /** Создать FAQ */
    post: operations["create_faq_api_v1_faq_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/faq/upload": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Загрузить FAQ из CSV
     * @description Загружает вопросы и ответы FAQ из CSV-файла.
     *     Ожидается CSV файл с колонками "Вопросы" и "Ответы".
     *     Пустая строка означает, что начинается новый вопрос.
     *     Первый вопрос в блоке становится основным,
     *     остальные - альтернативными формулировками (aliases).
     */
    post: operations["upload_faq_csv_api_v1_faq_upload_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/faq/{item_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Обновить FAQ по ID */
    put: operations["update_faq_api_v1_faq__item_id__put"]
    post?: never
    /** Удалить FAQ по ID */
    delete: operations["delete_faq_api_v1_faq__item_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/logs/request-stats": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Статистика количества запросов */
    get: operations["get_request_stats_api_v1_logs_request_stats_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/logs/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Получить логи сообщений
     * @description Получает логи сообщений с фильтрацией.
     *
     *     - **user_id**: фильтр по ID пользователя
     *     - **session_id**: фильтр по ID сессии
     *     - **message_type**: фильтр по типу сообщения
     *     - **limit**: количество записей (макс. 1000)
     *     - **offset**: сдвиг для пагинации
     */
    get: operations["get_message_logs_api_v1_logs__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/logs/session/{session_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Получить логи по сессии
     * @description Получает все логи для конкретной сессии.
     */
    get: operations["get_session_logs_api_v1_logs_session__session_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/logs/user/{user_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Получить логи по пользователю
     * @description Получает все логи для конкретного пользователя.
     */
    get: operations["get_user_logs_api_v1_logs_user__user_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/logs/type/{message_type}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Получить логи по типу сообщения
     * @description Получает логи по типу сообщения.
     *
     *     Возможные типы:
     *     - `user_input` - входящие сообщения от пользователей
     *     - `rag_context` - контекст полученный из RAG
     *     - `llm_response` - ответы от LLM
     *     - `faq_match` - совпадения из FAQ
     */
    get: operations["get_type_logs_api_v1_logs_type__message_type__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/logs/popular": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Получить самые популярные вопросы
     * @description Получает самые часто задаваемые вопросы пользователей.
     *
     *     - **limit**: максимальное количество возвращаемых вопросов
     */
    get: operations["get_popular_questions_api_v1_logs_popular_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/feedback": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Получить обращения обратной связи */
    get: operations["list_feedback_reports_api_v1_feedback_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/feedback/{report_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Получить обращение обратной связи */
    get: operations["get_feedback_report_api_v1_feedback__report_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Обновить статус обращения */
    patch: operations["update_feedback_report_status_api_v1_feedback__report_id__patch"]
    trace?: never
  }
  "/api/v1/rag/upload": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Загрузить документы в RAG */
    post: operations["upload_documents_to_rag_api_v1_rag_upload_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/rag/parse": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Спарсить страницу для RAG
     * @description Парсит страницу или PDF-документ, очищает текст через LLM и находит документы.
     */
    post: operations["parse_page_for_rag_api_v1_rag_parse_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/rag/confirm": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Подтвердить загрузку в RAG
     * @description Загружает отредактированный текст и выбранные документы в RAG.
     */
    post: operations["confirm_rag_upload_api_v1_rag_confirm_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/rag/preprocess": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Предобработать текст документа для RAG
     * @description Расширяет аббревиатуры и добавляет локальный контекст смысловым блокам.
     */
    post: operations["preprocess_document_for_rag_api_v1_rag_preprocess_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/rag/docs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Список документов в RAG
     * @description Возвращает список всех загруженных в RAG документов.
     */
    get: operations["list_rag_documents_api_v1_rag_docs_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/rag/docs/{doc_id}/content": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Получить полный текст документа
     * @description Возвращает полный исходный текст документа по его ID.
     */
    get: operations["get_rag_document_content_api_v1_rag_docs__doc_id__content_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/rag/docs/{doc_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Удалить документ из RAG
     * @description Удаляет документ из базы знаний RAG.
     */
    delete: operations["delete_rag_document_api_v1_rag_docs__doc_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/rag/docs/check": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Проверить документы RAG на изменения */
    post: operations["check_rag_documents_api_v1_rag_docs_check_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/rag/docs/update-changed": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Обновить измененные документы RAG */
    post: operations["update_changed_rag_documents_api_v1_rag_docs_update_changed_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/rag/upload/csv": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Импорт документов по ссылкам из CSV
     * @description Принимает CSV документ на вход и обрабатывает все документы там.
     *     Ожидаемый формат: Название,Link,Комментарий
     */
    post: operations["upload_csv_documents_api_v1_rag_upload_csv_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/rag/upload/csv/preview": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Превью документов из CSV (без обработки)
     * @description Принимает CSV документ и возвращает список найденных в нём ссылок без их обработки.
     */
    post: operations["preview_csv_documents_api_v1_rag_upload_csv_preview_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/rag/cache/clear": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Очистить кэш ответов RAG
     * @description Очищает кэш ответов LLM (kv_store_llm_response_cache.json)
     *     для графа, чтобы агент перестал отдавать старые ответы по старым данным.
     *     Очистка вызывается по нажатию кнопки администратором.
     */
    post: operations["clear_rag_cache_api_v1_rag_cache_clear_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/evals/run": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Run Evaluation */
    post: operations["run_evaluation_api_v1_evals_run_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/evals/status": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Route Get Evaluation Status */
    get: operations["route_get_evaluation_status_api_v1_evals_status_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stats/topics": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Topic Stats
     * @description Получить статистику по темам сообщений.
     */
    get: operations["get_topic_stats_api_v1_stats_topics_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/system-logs/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get System Logs
     * @description Получает последние N строк из указанного файла логов.
     */
    get: operations["get_system_logs_api_v1_system_logs__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/system-logs/files": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Log Files
     * @description Возвращает список доступных файлов логов.
     */
    get: operations["list_log_files_api_v1_system_logs_files_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/system-logs/download": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Download System Logs
     * @description Скачивает указанный файл логов.
     */
    get: operations["download_system_logs_api_v1_system_logs_download_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/users/count-stats": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Users Count Stats */
    get: operations["get_users_count_stats_api_v1_users_count_stats_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/messages": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Messages
     * @description Возвращает список сообщений и ответов бота.
     */
    get: operations["get_messages_api_v1_messages_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AbbrevItem */
    AbbrevItem: {
      /**
       * Id
       * @description UUID записи (заполняется при ответе)
       */
      id?: string | null
      /**
       * Short
       * @description Аббревиатура (например, НГУ)
       */
      short: string
      /**
       * Full
       * @description Расшифровка (например, Новосибирский государственный университет)
       */
      full: string
    }
    /** AbbrevListResponse */
    AbbrevListResponse: {
      /**
       * Items
       * @description Список аббревиатур
       */
      items: components["schemas"]["AbbrevItem"][]
    }
    /** AdminResponse */
    AdminResponse: {
      /** Id */
      id: string
      /** Username */
      username: string
      role: components["schemas"]["AdminRole"]
      /** Is Active */
      is_active: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Created By Id */
      created_by_id: string | null
    }
    /**
     * AdminRole
     * @enum {string}
     */
    AdminRole: "superadmin" | "admin" | "viewer"
    /** Body_preview_csv_documents_api_v1_rag_upload_csv_preview_post */
    Body_preview_csv_documents_api_v1_rag_upload_csv_preview_post: {
      /**
       * File
       * @description CSV файл с полями (Название, Link, Комментарий)
       */
      file: string
    }
    /** Body_upload_csv_documents_api_v1_rag_upload_csv_post */
    Body_upload_csv_documents_api_v1_rag_upload_csv_post: {
      /**
       * File
       * @description CSV файл с полями (Название, Link, Комментарий)
       */
      file: string
    }
    /** Body_upload_documents_to_rag_api_v1_rag_upload_post */
    Body_upload_documents_to_rag_api_v1_rag_upload_post: {
      /**
       * Files
       * @description Файлы для индексации в RAG
       */
      files: string[]
    }
    /** Body_upload_faq_csv_api_v1_faq_upload_post */
    Body_upload_faq_csv_api_v1_faq_upload_post: {
      /** File */
      file: string
    }
    /** ConfirmUploadRequest */
    ConfirmUploadRequest: {
      /**
       * Title
       * @description Название страницы
       */
      title: string
      /**
       * Url
       * @description URL страницы
       */
      url: string
      /**
       * Text
       * @description Отредактированный текст страницы
       */
      text: string
      /**
       * Documents
       * @description Финальный список файлов для загрузки
       */
      documents: components["schemas"]["ParsedDocument"][]
    }
    /** CsvImportPreviewResponse */
    CsvImportPreviewResponse: {
      /**
       * Total Found
       * @description Всего найдено ссылок в CSV
       */
      total_found: number
      /**
       * Results
       * @description Список найденных документов для превью
       */
      results: components["schemas"]["CsvImportPreviewResult"][]
    }
    /** CsvImportPreviewResult */
    CsvImportPreviewResult: {
      /**
       * Title
       * @description Название документа
       */
      title: string
      /**
       * Url
       * @description URL документа
       */
      url: string
      /**
       * Comment
       * @description Комментарий из CSV
       */
      comment?: string | null
    }
    /** CsvImportResponse */
    CsvImportResponse: {
      /**
       * Imported Count
       * @description Количество успешно импортированных документов
       */
      imported_count: number
      /**
       * Total Found
       * @description Всего найдено ссылок в CSV
       */
      total_found: number
      /**
       * Results
       * @description Результаты обработки по каждой ссылке
       */
      results: components["schemas"]["CsvImportResult"][]
    }
    /** CsvImportResult */
    CsvImportResult: {
      /**
       * Title
       * @description Название документа
       */
      title: string
      /**
       * Url
       * @description URL документа
       */
      url: string
      /**
       * Success
       * @description Статус обработки
       */
      success: boolean
      /**
       * Message
       * @description Сообщение об ошибке или статус
       */
      message?: string | null
    }
    /** DocumentCheckRequest */
    DocumentCheckRequest: {
      /**
       * Document Ids
       * @description ID документов для проверки; если не переданы, проверяются все
       */
      document_ids?: string[] | null
    }
    /** DocumentCheckResponse */
    DocumentCheckResponse: {
      /**
       * Checked Count
       * @description Количество проверенных документов
       */
      checked_count: number
      /**
       * Changed Count
       * @description Количество измененных документов
       */
      changed_count: number
      /**
       * Results
       * @description Результаты проверки
       */
      results: components["schemas"]["DocumentCheckResult"][]
    }
    /** DocumentCheckResult */
    DocumentCheckResult: {
      /**
       * Id
       * @description ID документа
       */
      id: string
      /**
       * Title
       * @description Название документа
       */
      title: string
      /**
       * Source Url
       * @description URL источника
       */
      source_url?: string | null
      /**
       * Status
       * @description changed, unchanged, skipped, failed, updated
       */
      status: string
      /**
       * Content Hash
       * @description Новый SHA-256
       */
      content_hash?: string | null
      /**
       * Previous Hash
       * @description Сохраненный SHA-256
       */
      previous_hash?: string | null
      /**
       * Message
       * @description Ошибка или пояснение
       */
      message?: string | null
    }
    /** DocumentUpdateResponse */
    DocumentUpdateResponse: {
      /**
       * Checked Count
       * @description Количество проверенных документов
       */
      checked_count: number
      /**
       * Updated Count
       * @description Количество обновленных документов
       */
      updated_count: number
      /**
       * Results
       * @description Результаты обновления
       */
      results: components["schemas"]["DocumentCheckResult"][]
    }
    /** FaqItem */
    FaqItem: {
      /**
       * Id
       * @description UUID записи (заполняется при ответе)
       */
      id?: string | null
      /**
       * Question
       * @description Основной вопрос
       */
      question: string
      /**
       * Aliases
       * @description Альтернативные формулировки (синонимы) вопроса
       */
      aliases?: string[]
      /**
       * Answer
       * @description Текст ответа
       */
      answer: string
    }
    /** FaqListResponse */
    FaqListResponse: {
      /**
       * Items
       * @description Список вопросов-ответов
       */
      items: components["schemas"]["FaqItem"][]
    }
    /** FeedbackReportListItem */
    FeedbackReportListItem: {
      /** Id */
      id: number
      /** User Id */
      user_id: number
      /** Session Id */
      session_id: string
      /** Channel */
      channel: string
      /** Comment */
      comment: string
      /** Question */
      question?: string | null
      /** Bot Response */
      bot_response?: string | null
      /** Status */
      status: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Reviewed At */
      reviewed_at?: string | null
    }
    /** FeedbackReportListResponse */
    FeedbackReportListResponse: {
      /** Reports */
      reports: components["schemas"]["FeedbackReportListItem"][]
      /** Total */
      total: number
      /** Limit */
      limit: number
      /** Offset */
      offset: number
    }
    /** FeedbackReportResponse */
    FeedbackReportResponse: {
      /** Id */
      id: number
      /** User Id */
      user_id: number
      /** Session Id */
      session_id: string
      /** Channel */
      channel: string
      /** Comment */
      comment: string
      /** Question */
      question?: string | null
      /** Bot Response */
      bot_response?: string | null
      /** Logs Snapshot */
      logs_snapshot?: {
        [key: string]: unknown
      }[] | null
      /** Status */
      status: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Reviewed At */
      reviewed_at?: string | null
    }
    /** FeedbackReportStatusUpdate */
    FeedbackReportStatusUpdate: {
      /**
       * Status
       * @enum {string}
       */
      status: "open" | "reviewed" | "ignored"
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** InviteCodeRequest */
    InviteCodeRequest: {
      /** @default admin */
      role: components["schemas"]["AdminRole"]
      /** Expires In Hours */
      expires_in_hours?: number | null
    }
    /** InviteCodeResponse */
    InviteCodeResponse: {
      /** Code */
      code: string
      role: components["schemas"]["AdminRole"]
      /** Expires At */
      expires_at: string | null
    }
    /** LoginRequest */
    LoginRequest: {
      /** Username */
      username: string
      /** Password */
      password: string
    }
    /**
     * MessageLogListResponse
     * @description Модель ответа для списка логов.
     */
    MessageLogListResponse: {
      /** Logs */
      logs: components["schemas"]["MessageLogResponse"][]
      /** Total */
      total: number
      /** Limit */
      limit: number
      /** Offset */
      offset: number
    }
    /**
     * MessageLogResponse
     * @description Модель ответа для лога сообщения.
     */
    MessageLogResponse: {
      /** Id */
      id: number
      /** User Id */
      user_id: number
      /** Session Id */
      session_id: string
      /** Message Type */
      message_type: string
      /** Content */
      content: string
      /** Message Metadata */
      message_metadata?: {
        [key: string]: unknown
      } | null
      /** Topic Id */
      topic_id?: number | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** MessageResponse */
    MessageResponse: {
      /** Id */
      id: string
      /** User Id */
      user_id: number
      /** Username */
      username?: string | null
      /** Messenger */
      messenger?: string | null
      /** Session Id */
      session_id: string
      /** User Text */
      user_text: string
      /** Bot Response */
      bot_response: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** ParsedDocument */
    ParsedDocument: {
      /**
       * Title
       * @description Название документа
       */
      title: string
      /**
       * Url
       * @description URL для скачивания/ссылки на документ
       */
      url: string
    }
    /** ParsedPageResult */
    ParsedPageResult: {
      /**
       * Title
       * @description Название страницы
       */
      title: string
      /**
       * Url
       * @description URL страницы
       */
      url: string
      /**
       * Text
       * @description Сырой или предобработанный текст страницы
       */
      text: string
      /**
       * Documents
       * @description Список найденных PDF-документов
       */
      documents: components["schemas"]["ParsedDocument"][]
    }
    /** PopularQuestion */
    PopularQuestion: {
      /** Question */
      question: string
      /** Count */
      count: number
    }
    /** PopularQuestionsResponse */
    PopularQuestionsResponse: {
      /** Questions */
      questions: components["schemas"]["PopularQuestion"][]
    }
    /** PreprocessDocumentRequest */
    PreprocessDocumentRequest: {
      /**
       * Text
       * @description Текст документа для предобработки
       */
      text: string
    }
    /** PreprocessDocumentResponse */
    PreprocessDocumentResponse: {
      /**
       * Text
       * @description Текст после расширения аббревиатур и очистки
       */
      text: string
      /**
       * Chars
       * @description Количество символов в обработанном тексте
       */
      chars: number
    }
    /** RagDocument */
    RagDocument: {
      /**
       * Id
       * @description Идентификатор документа (обычно URL или имя файла)
       */
      id: string
      /**
       * Title
       * @description Название документа
       */
      title?: string | null
      /**
       * Url
       * @description Оригинальный URL или путь к файлу
       */
      url?: string | null
      /**
       * Status
       * @description Статус обработки
       */
      status: string
      /**
       * Content Hash
       * @description SHA-256 сырого контента
       */
      content_hash?: string | null
      /**
       * Content Summary
       * @description Краткое содержание
       */
      content_summary?: string | null
      /**
       * Content Length
       * @description Длина контента
       */
      content_length?: number | null
      /**
       * Created At
       * @description Дата создания
       */
      created_at?: string | null
      /**
       * Updated At
       * @description Дата обновления
       */
      updated_at?: string | null
      /**
       * Last Indexed At
       * @description Дата последней индексации
       */
      last_indexed_at?: string | null
    }
    /** RagDocumentContentResponse */
    RagDocumentContentResponse: {
      /**
       * Id
       * @description Идентификатор документа
       */
      id: string
      /**
       * Content
       * @description Полный текст документа
       */
      content: string
    }
    /** RagDocumentListResponse */
    RagDocumentListResponse: {
      /**
       * Documents
       * @description Список документов в RAG
       */
      documents: components["schemas"]["RagDocument"][]
    }
    /** RagUploadResponse */
    RagUploadResponse: {
      /**
       * Accepted Formats
       * @description Поддерживаемые расширения файлов
       */
      accepted_formats: string[]
      /**
       * Indexed Count
       * @description Количество успешно проиндексированных файлов
       */
      indexed_count: number
      /**
       * Skipped Count
       * @description Количество пропущенных файлов
       */
      skipped_count: number
      /**
       * Results
       * @description Результаты обработки по каждому загруженному файлу
       */
      results: components["schemas"]["UploadedDocumentResult"][]
    }
    /** RegisterRequest */
    RegisterRequest: {
      /** Username */
      username: string
      /** Password */
      password: string
      /** Invite Code */
      invite_code?: string | null
    }
    /**
     * RequestCountBucket
     * @description Элемент статистики по количеству запросов.
     */
    RequestCountBucket: {
      /**
       * Period
       * Format: date-time
       */
      period: string
      /** Count */
      count: number
    }
    /**
     * RequestCountStatsResponse
     * @description Статистика количества запросов за период времени.
     */
    RequestCountStatsResponse: {
      /** Total */
      total: number
      /** Group By */
      group_by: string
      /** Start */
      start?: string | null
      /** End */
      end?: string | null
      /** Buckets */
      buckets: components["schemas"]["RequestCountBucket"][]
    }
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string
      /**
       * Token Type
       * @default bearer
       */
      token_type: string
    }
    /**
     * TopicCreate
     * @description Модель для создания новой темы.
     */
    TopicCreate: {
      /**
       * Label
       * @description Название темы
       */
      label: string
      /**
       * Description
       * @description Описание темы
       */
      description?: string | null
      /**
       * Is Active
       * @description Активна ли тема
       * @default true
       */
      is_active: boolean
    }
    /**
     * TopicListResponse
     * @description Модель ответа для списка тем.
     */
    TopicListResponse: {
      /** Topics */
      topics: components["schemas"]["TopicResponse"][]
      /** Total */
      total: number
    }
    /**
     * TopicResponse
     * @description Модель ответа для темы.
     */
    TopicResponse: {
      /**
       * Label
       * @description Название темы
       */
      label: string
      /**
       * Description
       * @description Описание темы
       */
      description?: string | null
      /** Id */
      id: number
      /** Is Active */
      is_active: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * TopicUpdate
     * @description Модель для обновления темы.
     */
    TopicUpdate: {
      /**
       * Label
       * @description Название темы
       */
      label?: string | null
      /**
       * Description
       * @description Описание темы
       */
      description?: string | null
      /**
       * Is Active
       * @description Активна ли тема
       */
      is_active?: boolean | null
    }
    /** UploadedDocumentResult */
    UploadedDocumentResult: {
      /**
       * Filename
       * @description Имя загруженного файла
       */
      filename: string
      /**
       * Status
       * @description Статус обработки: indexed или skipped
       */
      status: string
      /**
       * Message
       * @description Подробности результата обработки
       */
      message: string
      /**
       * Chars
       * @description Количество символов, отправленных в RAG
       * @default 0
       */
      chars: number
    }
    /** UserCountStatsResponse */
    UserCountStatsResponse: {
      /** Day */
      day: number
      /** Week */
      week: number
      /** Month */
      month: number
      /** Year */
      year: number
      /** All Time */
      all_time: number
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TokenResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AdminResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_me_api_v1_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AdminResponse"]
        }
      }
    }
  }
  create_invite_api_v1_auth_invite_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteCodeRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InviteCodeResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_admins_api_v1_auth_admins_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AdminResponse"][]
        }
      }
    }
  }
  deactivate_admin_api_v1_auth_admins__admin_id__deactivate_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        admin_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AdminResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_topics_api_v1_topics__get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TopicListResponse"]
        }
      }
    }
  }
  create_topic_api_v1_topics__post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TopicCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TopicResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_topic_api_v1_topics__topic_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        topic_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TopicResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_topic_api_v1_topics__topic_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        topic_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["TopicUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TopicResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_topic_api_v1_topics__topic_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        topic_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_all_api_v1_abbrev_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AbbrevListResponse"]
        }
      }
    }
  }
  create_api_v1_abbrev_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["AbbrevItem"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AbbrevItem"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_api_v1_abbrev__item_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["AbbrevItem"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AbbrevItem"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_api_v1_abbrev__item_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_all_faqs_api_v1_faq_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FaqListResponse"]
        }
      }
    }
  }
  create_faq_api_v1_faq_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["FaqItem"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FaqItem"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  upload_faq_csv_api_v1_faq_upload_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_faq_csv_api_v1_faq_upload_post"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FaqListResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_faq_api_v1_faq__item_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["FaqItem"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FaqItem"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_faq_api_v1_faq__item_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_request_stats_api_v1_logs_request_stats_get: {
    parameters: {
      query?: {
        /** @description Начало периода (ISO 8601) */
        start?: string | null
        /** @description Конец периода (ISO 8601) */
        end?: string | null
        /** @description Группировка: hour, day, week, month */
        group_by?: string
        /** @description Тип сообщения для статистики */
        message_type?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RequestCountStatsResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_message_logs_api_v1_logs__get: {
    parameters: {
      query?: {
        user_id?: number | null
        session_id?: string | null
        message_type?: string | null
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageLogListResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_session_logs_api_v1_logs_session__session_id__get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageLogListResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_user_logs_api_v1_logs_user__user_id__get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path: {
        user_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageLogListResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_type_logs_api_v1_logs_type__message_type__get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path: {
        message_type: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageLogListResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_popular_questions_api_v1_logs_popular_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PopularQuestionsResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_feedback_reports_api_v1_feedback_get: {
    parameters: {
      query?: {
        status?: ("open" | "reviewed" | "ignored") | null
        user_id?: number | null
        session_id?: string | null
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FeedbackReportListResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_feedback_report_api_v1_feedback__report_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        report_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FeedbackReportResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_feedback_report_status_api_v1_feedback__report_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        report_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeedbackReportStatusUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["FeedbackReportResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  upload_documents_to_rag_api_v1_rag_upload_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_documents_to_rag_api_v1_rag_upload_post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RagUploadResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  parse_page_for_rag_api_v1_rag_parse_post: {
    parameters: {
      query: {
        /** @description URL страницы */
        url: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ParsedPageResult"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  confirm_rag_upload_api_v1_rag_confirm_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmUploadRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  preprocess_document_for_rag_api_v1_rag_preprocess_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreprocessDocumentRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PreprocessDocumentResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_rag_documents_api_v1_rag_docs_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RagDocumentListResponse"]
        }
      }
    }
  }
  get_rag_document_content_api_v1_rag_docs__doc_id__content_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RagDocumentContentResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_rag_document_api_v1_rag_docs__doc_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  check_rag_documents_api_v1_rag_docs_check_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["DocumentCheckRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["DocumentCheckResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_changed_rag_documents_api_v1_rag_docs_update_changed_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": components["schemas"]["DocumentCheckRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["DocumentUpdateResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  upload_csv_documents_api_v1_rag_upload_csv_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_csv_documents_api_v1_rag_upload_csv_post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CsvImportResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  preview_csv_documents_api_v1_rag_upload_csv_preview_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_preview_csv_documents_api_v1_rag_upload_csv_preview_post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CsvImportPreviewResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  clear_rag_cache_api_v1_rag_cache_clear_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  run_evaluation_api_v1_evals_run_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  route_get_evaluation_status_api_v1_evals_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  get_topic_stats_api_v1_stats_topics_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: unknown
          }[]
        }
      }
    }
  }
  get_system_logs_api_v1_system_logs__get: {
    parameters: {
      query?: {
        /** @description Имя лог файла */
        filename?: string
        /** @description Количество последних строк */
        lines?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": string[]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_log_files_api_v1_system_logs_files_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": string[]
        }
      }
    }
  }
  download_system_logs_api_v1_system_logs_download_get: {
    parameters: {
      query?: {
        /** @description Имя лог файла */
        filename?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_users_count_stats_api_v1_users_count_stats_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserCountStatsResponse"]
        }
      }
    }
  }
  get_messages_api_v1_messages_get: {
    parameters: {
      query?: {
        /** @description Фильтр по user_id */
        user_id?: number | null
        /** @description Количество записей */
        limit?: number
        /** @description Смещение */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageResponse"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
}
